### ISSUE TITLE
Apache Age install required

### ISSUE THREAD

**Issue by calebl** [marpori/rails_age#1]
Maybe this should have been obvious, but I ran into errors when running bin/rails apache_age:install because I hadn't installed https://github.com/apache/age on my machine yet. I'll try to create a PR with updated documentation, just wanted to leave this here as a reminder

error looked like this:
`PG::FeatureNotSupported: ERROR:  extension "age" is not available`

**Comment by btihen** [comment]
Thanks, I will have added this to the documentation.
